### ISSUE TITLE
Creating a better README

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#1]
Hello there everyone! This is the first issue on my repo designed for new contributors and for the Hacktoberfest by DigitalOcean. Just some simple edits could be made to the README, but here are some suggestions:

- Aligning the logo
- Linking the demo site
- Writing about more of the components currently in the framework

Feel free to put in anything you see fit.

Thanks!

**Comment by ryanimpey** [comment]
Hi, I'll start on this now for you!

**Comment by cpdevelops** [comment]
Thanks @ryanimpey for the changes! This issue will be closed now.
