### ISSUE TITLE
Tweak Alerts

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#20]
As of today, I added the new component of alerts. Right now, it is a very rough component and can use a lot of work, in both the actual code of them and the design. It would be great if someone could take this over.

You can find the alerts component file in src/components/alerts.scss

Thanks!

**Comment by bhagatparwinder** [comment]
I'll take this. @cpdevelops can you assign this to me? Secondly, is the alert a popup or inline? I do not see it added to index.html (only a scss file exists)

**Comment by cpdevelops** [comment]
Thank you for wanting to take this over. I will go ahead and assign it to you.

It is an inline alert, and I attempted to add it to the demo site but there were too many merge conflicts so I decided to hold off on that. 

Some thing to note would be a JS based close button would be great, and you can take any creative freedom you want wether its the color of the entire layout.

Thanks for starting to contribute and happy coding.

**Comment by bhagatparwinder** [comment]
✅  Please refer https://github.com/cpdevelops/simple.css/pull/25

![image](https://user-images.githubusercontent.com/6809087/31140716-dc9fa724-a83a-11e7-94f6-19e56b814da2.png)

**Comment by cpdevelops** [comment]
Thanks for the PR @bhagatparwinder. Closing this issue now
