### ISSUE TITLE
Adding alerts to the README

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#29]
Trying to add some simple issues for people to complete for Hacktoberfest! The only task here is to adjust the components section in the README to add the new alerts component shown on the demo site. 

**PROJECT TAKEN OVER BY @CLJohnson088**

Thanks and happy coding!

**Comment by CLJohnson088** [comment]
I can look into adding that.

**Comment by cpdevelops** [comment]
Thanks @CLJohnson088 ! Please add the information in the same format as the current button information format and after the buttons. Thank you for wanting to take this over and happy coding!

**Comment by cpdevelops** [comment]
Completed in PR #32
