### ISSUE TITLE
Grid System

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#31]
Separating this from #4 since it is a large component. This is pretty much the same as the grid system used in the two frameworks of PotatoCSS and Bootstrap, but with a design similar to what is used now in the framework.

Thank you and please notify me if you would like to complete this task. Happy coding!

**Comment by lpraz** [comment]
How complex will the grid system be? Will it have different sizes for different screen widths? How far will you be able to divide columns (assuming this will be twelfths, since both Bootstrap and PotatoCSS use them as well)?

**Comment by cpdevelops** [comment]
> How complex will the grid system be?

Not too complex, just a basic system.

> Will it have different sizes for different screen widths?

Make it responsive if possible, but it isn't a current priority.

> How far will you be able to divide columns?

Twelfths is correct.

Are you planning on taking over this issue @lpraz?

**Comment by lpraz** [comment]
@cpdevelops Thanks! I'll take it, if nobody else has already.

**Comment by cpdevelops** [comment]
You're clear to get started @lpraz!

**Comment by lpraz** [comment]
Thanks! I'm almost finished, but I can't seem to get the build system to work. Up to this point, I've just been using Sass to compile the SCSS, but it doesn't provide a minified CSS file alongside the full one (to my knowledge). Since I'm new to using npm/gulp, what do I need to do to get that working?

**Comment by bobharley** [comment]
@cpdevelops I can help

**Comment by cpdevelops** [comment]
Sorry @bobharley , but we already have someone assigned to this. You can find another component listed in #4 if you would like to continue to help though.

**Comment by cpdevelops** [comment]
Added in PR #66
