### ISSUE TITLE
optimization of code  

### ISSUE THREAD

**Issue by soumam007** [cpdevelops/simple.css#45]
<h3 class="header-centered">What items does simple.css have?</h3> 

class =="header-centred" wasnt actually requirerd because we actually have alligned it to center, it can be removed.

Not a serious issue but if said can be optimized

**Comment by cpdevelops** [comment]
Thanks for telling me. I will get this fixed as soon as I can.

**Comment by soumam007** [comment]
Ok I will edit that tomorrow :)

**Comment by cpdevelops** [comment]
Fixed in #54
