### ISSUE TITLE
script file should be removed to its desired position

### ISSUE THREAD

**Issue by soumam007** [cpdevelops/simple.css#47]
Since we are looking on this development project like a Bootstrap project so we expect people to download our CSS/SCSS and JS file .
They will have their own index.html and they should be able to import these functionalities just by the class name. 
So if the script file is not given an appropriate position like say in a js folder then the motive of the project is not maintained.
I would recommend to follow the project structure like bootstrap itself.
css folder will have css files.
js foldeer will have js files.

and our index,html works as a showcase what we can do with these css and js already written

**Comment by dvlden** [comment]
This project does not contain any JS files at this point.

Adding CSS files in `dist/css/simple.min.css` and `dist/css/simple.css` at this stage seems redundant, doesn't it? Hence the structure to keep it without `css` folder inside of the `dist` for the time being, until some `js` arrives as well.

Can you clarify on what scripts did you meant at this stage of development?

Also, would be great if you can tell us more about the structure this project should be following?

**Comment by cpdevelops** [comment]
We can worry about this later. For now there is only a few lines of JS so it’s not a priority. Closing this issue,but it can be reopened later.

**Comment by soumam007** [comment]
Surely tomorrow I will elaborate to you what are my future thoughts regarding this project.

Basically I wanted to add a carousel slider class and as you know scripting within index.html is not what the project is meant for. 

But this is a serious issue but we can re open it later :)

**Comment by cpdevelops** [comment]
I do like the idea of a carousel slider component but since we have no similar components currently (carousel, modal, etc.) that require their own script files, this is not a priority issue and can be reopened later.

I would like to hear your thoughts on where you think this project should head, such as different adjustments you think we could make to the development process and components you think should be added.
