### ISSUE TITLE
Button size styling fix

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#5]
Minor issue, but I feel as though the different button sizes don't come out well. The large button seems smushed, the medium size seems too short, and the small one doesn't even exist yet! If someone would like to help find a padding size that looks great for them that would be great. 

Note: Be sure to just update the class styling in simple.css for the different sizes instead of creating new ones, and when creating the small size button be sure to follow the current style of class names.

**Comment by faraazahmad** [comment]
I can fix this!

**Comment by C-Lodder** [comment]
Some size modifiers: https://github.com/cpdevelops/simple.css/pull/6

**Comment by cpdevelops** [comment]
Fixed by @C-Lodder in PR #6
