### ISSUE TITLE
logo.svg in the website will be too large

### ISSUE THREAD

**Issue by soumam007** [cpdevelops/simple.css#53]
Are you going to work on this ?
**NO**

I am not so familiar with svg formats, so who is familiar please reduce its size in the website

![screenshot from 2017-10-05 13-26-18](https://user-images.githubusercontent.com/21683311/31216336-e5fdcdfe-a9d0-11e7-83bb-de5f33ceaf28.png)

^^^

**Comment by cpdevelops** [comment]
Can be discussed in #52. Closing this issue.
