### ISSUE TITLE
Alert Component - Spacing issue

### ISSUE THREAD

**Issue by dvlden** [cpdevelops/simple.css#55]
**Explanation:**
When on higher resolution screen which it has bad spacing between close button and content. I know this wouldn't be an issue when `.container` is created, but it would be in `.container-flex`. At this point, there's no limited width in example site, so it's good as the issue can be noticed.

** Preview: **
<img width="1920" alt="screen shot 2017-10-05 at 15 06 21" src="https://user-images.githubusercontent.com/3460368/31228767-e84255ae-a9de-11e7-9fda-a207af8374ad.png">

**How to fix?**
Find `.alert` component, search for `justify-content: center` and replace it with `justify-content: space-between`.

<img width="1920" alt="screen shot 2017-10-05 at 15 11 31" src="https://user-images.githubusercontent.com/3460368/31228952-8280602a-a9df-11e7-8933-4e31a0902923.png">

> fork, do changes, compile, commit, create pull request... Please follow `CONTRIBUTING.md` file if you are struggling...

**Comment by wwwebneko** [comment]
@dvlden I will work on it
