### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by C-Lodder** [cpdevelops/simple.css#57]
It's 2017, absolutely no need to use jQuery

https://github.com/cpdevelops/simple.css/blob/master/src/scripts/simple.js

**Comment by dvlden** [comment]
Still, many projects use it. It's helpful for quick prototyping too...
I agree with this, but as spoken with the project owner, when framework grows bigger and starts getting more scripts into it, jQuery will be removed and modularity will be implemented.

**Comment by C-Lodder** [comment]
Using jQuery to start and then moving to vanilla JS is **not** a good approach at all. Frameworks spend ages doing this.

The script mentioned above would take 5 minutes to convert to vanilla JS

**Comment by dvlden** [comment]
If you'd like to work on it, feel free to do so and submit PR. 
Although, I'm okay with 3 simple lines of code as for now...
