### ISSUE TITLE
Enforce adding to demo

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#59]
Something that I keep forgetting to do is making sure that contributors submitting PRs aren't always adding their new components // changes to the README or demo. This should probably be added to the CONTRIBUTING file and enforced before merging so that it isn't a task for later.

I will take this over or @dvlden can if he would like to.

**Comment by dvlden** [comment]
Go ahead man, improve `CONTRIBUTING.md`... 
I think we should not, however, add the HTML snippets into `README.md`. It will get bulky quickly.

Maybe there should be only that demo file, `index.html`, which could later on become divided into different categories for each component, but for now a single file, where you won't show just a live demo, but also a code snippet.

Does that seem right to you?

**Comment by cpdevelops** [comment]
I do think that the README is already bulky and I love the idea of adding the code snippets into the index.html. I will assign myself to both of these tasks and will get them done as soon as I have the time. Thank you for the suggestion.

**Comment by cpdevelops** [comment]
Closing this issue as it will be changed in a new issue.
