### ISSUE TITLE
Code Snippets in index.html

### ISSUE THREAD

**Issue by cpdevelops** [cpdevelops/simple.css#62]
Plans for documentation to be moved over to Github Pages, will be assigned to me and @dvlden for now.

**Comment by cpdevelops** [comment]
The contributors most likely able to help are:

@cpdevelops

**Comment by joshuafbarker** [comment]
I can assist with this if need be. I did this with one of my repo's.

https://github.com/joshuafbarker/basic-static-server

**Comment by cpdevelops** [comment]
Reopening with more detail in a new issue.
