### ISSUE TITLE
Use the SCSS preprocessor

### ISSUE THREAD

**Issue by C-Lodder** [cpdevelops/simple.css#7]
Using SCSS for your framework will make life much easier, as you'll be able to utilise variables, functions, mixins, loops, etc..

**Comment by cpdevelops** [comment]
I was wanting to work with SCSS or SASS for a preprocessor, but that would take an entire rewrite of the current system. If someone would be willing to take over that task, that would be great. It would also be good to have two folders, one with the current SCSS file, and the other with the current compiled CSS file. 

If anyone wants to take over this, just tell me and I will add you as an assignee!

**Comment by andrewbash** [comment]
I can work on this if you'd like.

**Comment by cpdevelops** [comment]
That would be great @andrewbash. Thank you. I will assign you on this issue.

**Comment by cpdevelops** [comment]
That would be great @andrewbash. Thank you.

**Comment by dvlden** [comment]
I am working on this already.
However, as a project is so tiny/small at this point, I will create an empty file for variables as storage for you to use later on.

**Comment by dvlden** [comment]
Already done...

**Comment by cpdevelops** [comment]
@dvlden Thank you so much for your issue fixes. This will help us out a lot, and I hope you continue to help out in the future. I will close this issue now.
