### ISSUE TITLE
Insecure connection

### ISSUE THREAD

**Issue by C-Lodder** [cpdevelops/simple.css#72]
When clicking on the link in the screeny below, I get `Insecure connection`

![screenshot-2017-10-9 cpdevelops simple css](https://user-images.githubusercontent.com/2019801/31357755-fa4d3c46-ad3a-11e7-84e7-56c13f926fdc.png)

Either use `http` or update your SSL certificate

**Comment by cpdevelops** [comment]
The contributors most likely able to help are:

@cpdevelops

**Comment by cpdevelops** [comment]
Fixed by switching to http.

**Comment by soumam007** [comment]
can we switch to https? just askinng. I guess github has this facility
@cpdevelops @C-Lodder

**Comment by C-Lodder** [comment]
You can generate Github docs which use the https protocol, however the docs/demo appear to be on the authors personal server

**Comment by dvlden** [comment]
@cpdevelops - Just use "Let's Encrypt" on your server if you're not willing to switch to `gh-pages`.
