### ISSUE TITLE
Add gulp,scss documentation in readme

### ISSUE THREAD

**Issue by soumam007** [cpdevelops/simple.css#74]
I cant convertmy scss file to css , tough i have completed my work on list.
That works fine if i am writing directly in simple.css, but since the struvture has changed i need to convert it, which i am failing.
@cpdevelops @dvlden

**Comment by cpdevelops** [comment]
The contributors most likely able to help are:

@cpdevelops

**Comment by dvlden** [comment]
Will update development documentation file.
