### ISSUE TITLE
check node_modules/normalize.css

### ISSUE THREAD

**Issue by soumam007** [cpdevelops/simple.css#77]
20:17 : simple.css $ sass --watch src/styles/simple.scss:dist/simple.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error src/styles/simple.scss (Line 1: File to import not found or unreadable: node_modules/normalize.css/normalize.)

I did a npm install to download the dependencies, still I don't know why i was getting that

**Comment by cpdevelops** [comment]
The contributors most likely able to help are:

@cpdevelops
@dvlden

**Comment by cpdevelops** [comment]
I believe that you are supposed to run ```npm run dev & npm run watch``` during development and ```npm run prod``` when you are ready to compile and use, instead of compiling through sass.

**Comment by soumam007** [comment]
yes you can close that ,yeah i also think that last step which i did was the reason for it.
But i am not sure, if you think that , uncomment the line in variable.scss
i was using sass --watch where as @dvlden uses localhost during npm run dev && npm run watch.
So there was a clash.

**Comment by cpdevelops** [comment]
@soumam007 Can this issue be closed now?

**Comment by soumam007** [comment]
Yeah,sure @cpdevelops

**Comment by cpdevelops** [comment]
Thanks for responding. Closing now.
