### ISSUE TITLE
Add githooks for minification

### ISSUE THREAD

**Issue by tmarkovic** [cpdevelops/simple.css#9]
If this project grows (which I hope it does) wouldn’t it be nice prepare it with something like gulp to create a minified versiob for production?

**Comment by cpdevelops** [comment]
I hope it grows too, and thanks for the support. 

I don't have much experience with making CSS frameworks, but I feel like it would be better to do a minified version for full release. But running it by compiling when someone makes a change would be great, and would work similarly to #7 with the organization (SCSS folder, CSS folder, min folder). 

If you @tmarkovic , or anyone else, want to get into working on this, I can make you the assignee and you can go ahead and get started.

**Comment by tmarkovic** [comment]
I’ll get to it! I don’t have to much scss experience (or any other preprocessors) But I’m thinking that maybe there should also be some sort of style guide/naming convention in place also? Maybe look at other frameworks for inspiration on organization etc?

**Comment by cpdevelops** [comment]
Yes, a naming convention would definitely need to be created. I will get to thinking about it. Currently, there is no SCSS in place, so you can just work on getting a minifier setup for now and do an SCSS compiler later. Thanks for being so willing to help!

**Comment by tmarkovic** [comment]
Sounds great! I’ve been trying to get into oss-contributing for almost a year now and this project of yours felt really inviting and friendly so I finally jumped the gun.

Are you planning on taking this to npm/cdn? I have some experience setting up CI/CD-piplines and would love to help out!

If so, should I open up separate issues so people can work on different parts of CI/CD?

**Comment by cpdevelops** [comment]
Thanks for the kind words and I am glad you chose this project to contribute to first. 

I was hoping to eventually get it on CDN, and potentially NPM but I do not think that the project is currently even close to ready for that. For now, I would stick to the current issues and creating more components and eventually move to that stuff.

**Comment by tmarkovic** [comment]
@cpdevelops While I do respectfully disagree that it's ever to early to set up a workflow I see your point!

My main concern here is keeping the minified version under version control (in sync), but maybe that can be solved by using something like https://github.com/typicode/husky to enforce a minified build before pushing?

**Comment by cpdevelops** [comment]
That looks like it would work very well @tmarkovic. I don't have much experience in setting up these types of things, so it would be great if you could get started on working on both of these.

**Comment by dvlden** [comment]
You can now minify file for production by initiating command `npm run prod`. I did not made it so it compiles both minified and non-minified version, but it can easily be tweaked.

While developing:
`npm run dev && npm run watch`

When done and ready to push:
`npm run prod`

**Comment by cpdevelops** [comment]
@dvlden Thank you for your contribution. Your pull request has been merged, and I hope you stay and keep contributing to the project.

@tmarkovic Since @dvlden has successfully written gulp scripts to minify the file, the only job this task has left is the enforced minified build you suggested using husky. Whenever you are ready, you can get to work on that. 

Thanks.

**Comment by tmarkovic** [comment]
Nice job @dvlden !

Though I would like to point out that it would have been nice with a heads up since I started to work on this. Maybe something to have in mind for further contributions? 

Nonetheless, well done 👍

**Comment by cpdevelops** [comment]
Yes, that is something I have been thinking about since I have received multiple PRs for the same issues. A good method would be to have just one person call out that they want to accomplish that task, and then have them be the assignee to the issue so that everyone knows who is doing what.

**Comment by cpdevelops** [comment]
@dvlden I did not see the comment you made earlier saying 

> I did not made it so it compiles both minified and non-minified version, but it can easily be tweaked.

Is there any chance you would be able to work on that while @tmarkovic works on forcing a minified version for a PR? Thanks.

**Comment by dvlden** [comment]
Sure, I'll make an update where both minified and the non-minified file will be compiled for production.
